# Generated by Django 4.0 on 2021-12-31 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=10, unique=True)),
                ('phone', models.IntegerField(max_length=10)),
                ('companyname', models.CharField(max_length=20)),
                ('describtion_on_team', models.TextField(max_length=100)),
                ('describtion_on_company', models.TextField(max_length=100)),
                ('unique_about_solution', models.TextField(max_length=100)),
                ('value_proportion_for_customer', models.TextField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=2, unique=True)),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.application')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
