# Generated by Django 4.0 on 2022-01-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_application_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='companylogo',
            field=models.ImageField(max_length=20, null=True, upload_to=''),
        ),
    ]
