# Generated by Django 4.0 on 2022-01-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_application_companylogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='companylogo',
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
